"""
Two complementary hardening strategies:

1. Adversarial training — retrain the GBM classifier (in the same
   scaler+PCA feature space) on original data augmented with the
   adversarial examples generated in attacks.py, correctly labelled.

2. Physical feature-bound validation — an IoT-specific input gate.
   Network-flow features have hard physical constraints (packet counts
   can't be negative, TTL can't exceed 255, protocol one-hot flags can't
   be fractional). An attacker perturbing raw features to fool the model
   will often violate these constraints even if the PCA-space perturbation
   looks "small". This gate operates upstream of the model and needs no
   retraining, so it complements adversarial training rather than
   replacing it.
"""
import warnings
warnings.filterwarnings("ignore")

import joblib
import numpy as np
import pandas as pd
import tensorflow as tf
from art.attacks.evasion import FastGradientMethod
from art.estimators.classification import KerasClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score

from data_gen import FEATURE_BOUNDS, generate_iot_dataset

MODEL_DIR = "/home/claude/iotsentinel-adversarial/models"
RESULTS_DIR = "/home/claude/iotsentinel-adversarial/results"


def report(y_true, y_pred, label: str):
    print(f"\n--- {label} ---")
    print(f"accuracy : {accuracy_score(y_true, y_pred):.4f}")
    print(f"precision: {precision_score(y_true, y_pred, zero_division=0):.4f}")
    print(f"recall   : {recall_score(y_true, y_pred, zero_division=0):.4f}")
    print(f"f1       : {f1_score(y_true, y_pred, zero_division=0):.4f}")


# ---------------------------------------------------------------------------
# 1. Adversarial training
# ---------------------------------------------------------------------------

def adversarial_training():
    pipeline = joblib.load(f"{MODEL_DIR}/baseline_gbm.joblib")
    X_test = pd.read_csv(f"{MODEL_DIR}/X_test.csv")
    y_test = pd.read_csv(f"{MODEL_DIR}/y_test.csv").squeeze()

    # Re-derive the same train split used in baseline_model.py
    df = pd.read_csv("/home/claude/iotsentinel-adversarial/data/iot_flows.csv")
    X_full, y_full = df.drop(columns=["label"]), df["label"]
    from sklearn.model_selection import train_test_split
    X_train, _, y_train, _ = train_test_split(
        X_full, y_full, test_size=0.25, stratify=y_full, random_state=42
    )
    from imblearn.over_sampling import SMOTE
    X_train_res, y_train_res = SMOTE(random_state=42).fit_resample(X_train, y_train)

    pre = pipeline[:-1]  # frozen scaler + PCA
    X_train_pca = pre.transform(X_train_res)

    # Pull in the adversarial examples generated by attacks.py, all correctly
    # labelled with the ground-truth y_test they were crafted from.
    X_adv_fgsm = np.load(f"{RESULTS_DIR}/X_adv_fgsm.npy")
    X_adv_pgd = np.load(f"{RESULTS_DIR}/X_adv_pgd.npy")
    X_adv_hsj = np.load(f"{RESULTS_DIR}/X_adv_hsj.npy")
    y_adv_hsj = y_test.values[: len(X_adv_hsj)]

    X_aug = np.vstack([X_train_pca, X_adv_fgsm, X_adv_pgd, X_adv_hsj])
    y_aug = np.concatenate([y_train_res, y_test.values, y_test.values, y_adv_hsj])

    hardened_clf = GradientBoostingClassifier(
        n_estimators=200, max_depth=4, learning_rate=0.1, random_state=42
    )
    hardened_clf.fit(X_aug, y_aug)

    # Evaluate on clean test set
    X_test_pca = pre.transform(X_test)
    report(y_test, hardened_clf.predict(X_test_pca), "Hardened GBM — clean test set")

    # Re-evaluate against the same adversarial examples used in attacks.py
    report(y_test, hardened_clf.predict(X_adv_fgsm), "Hardened GBM — FGSM examples (was 67% acc pre-hardening)")
    report(y_test, hardened_clf.predict(X_adv_pgd), "Hardened GBM — PGD examples (was 65% acc pre-hardening)")
    report(y_adv_hsj, hardened_clf.predict(X_adv_hsj), "Hardened GBM — HopSkipJump examples (was 17% acc pre-hardening)")

    joblib.dump(hardened_clf, f"{MODEL_DIR}/hardened_gbm_clf.joblib")
    print(f"\nSaved hardened classifier -> {MODEL_DIR}/hardened_gbm_clf.joblib")


# ---------------------------------------------------------------------------
# 2. Physical feature-bound validation gate
# ---------------------------------------------------------------------------

def validate_bounds(X_raw: pd.DataFrame) -> pd.Series:
    """Return a boolean mask: True = physically plausible row, False = reject."""
    valid = pd.Series(True, index=X_raw.index)
    for col, (lo, hi) in FEATURE_BOUNDS.items():
        if col not in X_raw.columns:
            continue
        if lo is not None:
            valid &= X_raw[col] >= lo
        if hi is not None:
            valid &= X_raw[col] <= hi
    return valid


def demo_bound_gate():
    """Craft an FGSM attack directly in raw feature space (no PCA) and show
    how many resulting adversarial flows the bound gate catches before they
    ever reach the model."""
    df = generate_iot_dataset(n_samples=6000, random_state=7)
    X, y = df.drop(columns=["label"]), df["label"].values

    surrogate = tf.keras.Sequential([
        tf.keras.layers.Input(shape=(X.shape[1],)),
        tf.keras.layers.Dense(64, activation="relu"),
        tf.keras.layers.Dense(32, activation="relu"),
        tf.keras.layers.Dense(2, activation="softmax"),
    ])
    surrogate.compile(optimizer="adam", loss="sparse_categorical_crossentropy", metrics=["accuracy"])
    surrogate.fit(X.values, y, epochs=10, batch_size=64, verbose=0)

    art_classifier = KerasClassifier(model=surrogate, clip_values=(X.values.min(), X.values.max()))
    attack = FastGradientMethod(estimator=art_classifier, eps=0.5)
    X_adv_raw = attack.generate(x=X.values)
    X_adv_df = pd.DataFrame(X_adv_raw, columns=X.columns)

    mask_valid = validate_bounds(X_adv_df)
    n_total = len(X_adv_df)
    n_rejected = (~mask_valid).sum()

    print(f"\n--- Physical feature-bound gate (raw feature space) ---")
    print(f"Adversarial flows generated : {n_total}")
    print(f"Rejected as implausible     : {n_rejected} ({n_rejected/n_total:.1%})")
    print(f"Passed through undetected   : {n_total - n_rejected} ({(n_total-n_rejected)/n_total:.1%})")

    # Of the ones that passed the gate, how many still fool the surrogate?
    passed = X_adv_df[mask_valid].values
    if len(passed) > 0:
        preds_passed = np.argmax(surrogate.predict(passed, verbose=0), axis=1)
        true_passed = y[mask_valid.values]
        report(true_passed, preds_passed, "Surrogate accuracy on adversarial flows that passed the gate")


def main():
    adversarial_training()
    demo_bound_gate()


if __name__ == "__main__":
    main()
